name: Update Changelog
on:
  release:
    types: [published]
jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Update CHANGELOG.md
        run: |
          echo "${{ github.event.release.body }}\n\n$(cat CHANGELOG.md)" > CHANGELOG.md

      - name: Commit and Push
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add CHANGELOG.md
          git commit -m "docs: update changelog for ${{ github.event.release.tag_name }}"
          git push
